name: Maintenance
description: Suggest an activity to help address technical debt.
title: "Maintenance: TITLE"
labels: ["internal", "triage"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to help us proactively improve delivery velocity, safely.
  - type: textarea
    id: importance
    attributes:
      label: Why is this needed?
      description: Please help us understand the value so we can prioritize it accordingly
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Which area does this relate to?
      multiple: true
      options:
        - Tests
        - Infrastructure
        - Product
        - Governance
        - Security
        - Documentation
        - Other
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.
